project-includes = ["image_generation.py", "gemini_image_generation.py", "tests"]
project-excludes = ["**/__pycache__", "**/*venv/**", "**/.*/**"]
python-version = "3.14"
preset = "strict"

[errors]
missing-attribute = "ignore"
non-exhaustive-match = "error"
not-callable = "ignore"
not-iterable = "ignore"
